<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Iphp\ContentBundle\Entity;

use Iphp\ContentBundle\Entity\BaseContent as BaseContent;
use TooBig\AppBundle\Entity\Brand;
use TooBig\AppBundle\Entity\Color;
use TooBig\AppBundle\Entity\RateComment;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author malsn malsn@rambler.ru
 */
class Content extends BaseContent
{
    /**
     * @var int $id
     */
    protected $id;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->links = new ArrayCollection();

        $this->filesMedia = new ArrayCollection();
        $this->imagesMedia = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
}
