imports:
    - { resource: bundle/sonata_admin.yml }
    - { resource: bundle/sonata_block.yml }
    - { resource: bundle/genemu_form.yml }
    - { resource: bundle/fos_user.yml }
    - { resource: bundle/stof_doctrineextensions.yml }


assetic:
   bundles: [ IphpCoreBundle ]

parameters:
    iphp.content.block.announces.class: Application\Iphp\ContentBundle\Block\ContentAnnouncesBlockService

twig:
   form:
       resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
