<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Iphp\CoreBundle\Entity;

use Iphp\CoreBundle\Entity\BaseRubric as BaseRubric;
use TooBig\AppBundle\Entity\SizeType;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Rubric extends BaseRubric
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var SizeType $size_type
     */
    protected $size_type;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return SizeType
     */
    public function getSizeType()
    {
        return $this->size_type;
    }

    /**
     * @param SizeType $size_type
     */
    public function setSizeType($size_type)
    {
        $this->size_type = $size_type;
    }
}
