too_big_app:
    resource: "@TooBigAppBundle/Resources/config/routing.yml"
    prefix:   /

_main:
    resource: "@IphpCoreBundle/Resources/config/routing.yml"

fos_user_all:
    resource: "@IphpCoreBundle/Resources/config/routing/fos_user.yml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /