<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace TooBig\AppBundle\Entity;

use Iphp\ContentBundle\Entity\BaseContentImageMedia as ContentImageMedia;
use TooBig\AppBundle\Entity\Item;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class ItemImageMedia extends ContentImageMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var Item
     */
    protected $item; /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \TooBig\AppBundle\Entity\Item
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * @param \TooBig\AppBundle\Entity\Item $item
     */
    public function setItem($item)
    {
        $this->item = $item;
    }


}
