<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace TooBig\AppBundle\Entity;

use TooBig\AppBundle\Model\BaseItem as BaseItem;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author malsn malsn@rambler.ru
 */
class Item extends BaseItem
{
    protected $id;

    /**
     * @var integer
     */
    private $stateId;

    /**
     * @var integer
     */
    private $price;

    /**
     * @var \DateTime
     */
    protected $editedAt;
    /**
     * @var \DateTime
     */
    private $publicationDateEnd;

    /**
     * @var integer
     */
    private $hits;

    /**
     * @var string
     */
    private $logs;

    /**
     * @var string
     */
    private $phone;

    /**
     * @var string
     */
    private $place;

    /**
     * @var $place_geo_lat
     */
    protected $place_geo_lat;

    /**
     * @var $place_geo_lon
     */
    protected $place_geo_lon;

    /**
     * @var string
     */
    private $status;

    /**
     * @var Brand
     */
    private $brand;


    /**
     * @var Model
     */
    private $model;

    /**
     * @var Color
     */

    private $color;

    /**
     * @var SizeType
     */
    private $size_type;

    /**
     * @var Size
     */
    private $size;

    /**
     * @var string
     */
    private $gender;

    /**
     * @var RateComment[]
     */
    protected $rateComments;

    /**
     * @var ItemBlueimp[]
     */
    protected $blueimpImages;


    public function __construct()
    {
        parent::__construct();
        $this->rateComments = new ArrayCollection();
        $this->blueimpImages = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Color
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * @param Color $color
     */
    public function setColor($color)
    {
        $this->color = $color;
    }

    /**
     * @return int
     */
    public function getStateId()
    {
        return $this->stateId;
    }

    /**
     * @param int $stateId
     */
    public function setStateId($stateId)
    {
        $this->stateId = $stateId;
    }

    /**
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param int $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * @return string
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * @param string $place
     */
    public function setPlace($place)
    {
        $this->place = $place;
    }

    /**
     * @return mixed
     */
    public function getPlaceGeoLat()
    {
        return $this->place_geo_lat;
    }

    /**
     * @param mixed $place_geo_lat
     */
    public function setPlaceGeoLat($place_geo_lat)
    {
        $this->place_geo_lat = $place_geo_lat;
    }

    /**
     * @return mixed
     */
    public function getPlaceGeoLon()
    {
        return $this->place_geo_lon;
    }

    /**
     * @param mixed $place_geo_lon
     */
    public function setPlaceGeoLon($place_geo_lon)
    {
        $this->place_geo_lon = $place_geo_lon;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return \DateTime
     */
    public function getEditedAt()
    {
        return $this->editedAt;
    }

    /**
     * @param \DateTime $editedAt
     */
    public function setEditedAt($editedAt)
    {
        $this->editedAt = $editedAt;
    }

    /**
     * @return \DateTime
     */
    public function getPublicationDateEnd()
    {
        return $this->publicationDateEnd;
    }

    /**
     * @param \DateTime $publicationDateEnd
     */
    public function setPublicationDateEnd($publicationDateEnd)
    {
        $this->publicationDateEnd = $publicationDateEnd;
    }

    /**
     * @return int
     */
    public function getHits()
    {
        return $this->hits;
    }

    /**
     * @param int $hits
     */
    public function setHits($hits)
    {
        $this->hits = $hits;
    }

    /**
     * @return string
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * @param string $logs
     */
    public function setLogs($logs)
    {
        $this->logs = $logs;
    }

    /**
     * @return Brand
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * @param Brand $brand
     */
    public function setBrand($brand)
    {
        $this->brand = $brand;
    }

    /**
     * @return Model
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param Model $model
     */
    public function setModel($model)
    {
        $this->model = $model;
    }

    /**
     * @return SizeType
     */
    public function getSizeType()
    {
        return $this->size_type;
    }

    /**
     * @param SizeType $size_type
     */
    public function setSizeType($size_type)
    {
        $this->size_type = $size_type;
    }

    /**
     * @return Size
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @param Size $size
     */
    public function setSize($size)
    {
        $this->size = $size;
    }

    /**
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param string $gender
     */
    public function setGender($gender)
    {
        $this->gender = $gender;
    }

    /**
     * @return ItemBlueimp[]
     */
    public function getBlueimpImages()
    {
        return $this->blueimpImages;
    }

    /**
     * @param ItemBlueimp[] $blueimpImages
     */
    public function setBlueimpImages($blueimpImages)
    {
        $this->blueimpImages = $blueimpImages;
    }




}
