<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ClassificationBundle\Entity;

use Sonata\ClassificationBundle\Entity\BaseCategory as BaseCategory;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Category extends BaseCategory
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setSlug($slug)
    {
        $char_map = array(
            // Latin
            '?' => 'A', '?' => 'A', '?' => 'A', '?' => 'A', '?' => 'A', '?' => 'A', '?' => 'AE', '?' => 'C',
            '?' => 'E', '?' => 'E', '?' => 'E', '?' => 'E', '?' => 'I', '?' => 'I', '?' => 'I', '?' => 'I',
            '?' => 'D', '?' => 'N', '?' => 'O', '?' => 'O', '?' => 'O', '?' => 'O', '?' => 'O', '?' => 'O',
            '?' => 'O', '?' => 'U', '?' => 'U', '?' => 'U', '?' => 'U', '?' => 'U', '?' => 'Y', '?' => 'TH',
            '?' => 'ss',
            '?' => 'a', '?' => 'a', '?' => 'a', '?' => 'a', '?' => 'a', '?' => 'a', '?' => 'ae', '?' => 'c',
            '?' => 'e', '?' => 'e', '?' => 'e', '?' => 'e', '?' => 'i', '?' => 'i', '?' => 'i', '?' => 'i',
            '?' => 'd', '?' => 'n', '?' => 'o', '?' => 'o', '?' => 'o', '?' => 'o', '?' => 'o', '?' => 'o',
            '?' => 'o', '?' => 'u', '?' => 'u', '?' => 'u', '?' => 'u', '?' => 'u', '?' => 'y', '?' => 'th',
            '?' => 'y',
            // Russian
            'À' => 'A', 'Á' => 'B', 'Â' => 'V', 'Ã' => 'G', 'Ä' => 'D', 'Å' => 'E', '¨' => 'Yo', 'Æ' => 'Zh',
            'Ç' => 'Z', 'È' => 'I', 'É' => 'J', 'Ê' => 'K', 'Ë' => 'L', 'Ì' => 'M', 'Í' => 'N', 'Î' => 'O',
            'Ï' => 'P', 'Ð' => 'R', 'Ñ' => 'S', 'Ò' => 'T', 'Ó' => 'U', 'Ô' => 'F', 'Õ' => 'H', 'Ö' => 'C',
            '×' => 'Ch', 'Ø' => 'Sh', 'Ù' => 'Sh', 'Ú' => '', 'Û' => 'Y', 'Ü' => '', 'Ý' => 'E', 'Þ' => 'Yu',
            'ß' => 'Ya',
            'à' => 'a', 'á' => 'b', 'â' => 'v', 'ã' => 'g', 'ä' => 'd', 'å' => 'e', '¸' => 'yo', 'æ' => 'zh',
            'ç' => 'z', 'è' => 'i', 'é' => 'j', 'ê' => 'k', 'ë' => 'l', 'ì' => 'm', 'í' => 'n', 'î' => 'o',
            'ï' => 'p', 'ð' => 'r', 'ñ' => 's', 'ò' => 't', 'ó' => 'u', 'ô' => 'f', 'õ' => 'h', 'ö' => 'c',
            '÷' => 'ch', 'ø' => 'sh', 'ù' => 'sh', 'ú' => '', 'û' => 'y', 'ü' => '', 'ý' => 'e', 'þ' => 'yu',
            'ÿ' => 'ya');
        $slug = str_replace(array_keys($char_map), $char_map, $slug);
        $this->slug = Tag::slugify($slug);
    }
}
