<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Application\Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var $place
     */
    protected $place;

    /**
     * @var $place_geo_lat
     */
    protected $place_geo_lat;

    /**
     * @var $place_geo_lon
     */
    protected $place_geo_lon;

    /**
     * @var watchItems[]
     */
    protected $watchItems;

    /**
     * @var subscriptions[]
     */
    protected $subscriptions;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * @param $place
     */
    public function setPlace($place)
    {
        $this->place = $place;
    }

    /**
     * @return mixed
     */
    public function getPlaceGeoLat()
    {
        return $this->place_geo_lat;
    }

    /**
     * @param mixed $place_geo_lat
     */
    public function setPlaceGeoLat($place_geo_lat)
    {
        $this->place_geo_lat = $place_geo_lat;
    }

    /**
     * @return mixed
     */
    public function getPlaceGeoLon()
    {
        return $this->place_geo_lon;
    }

    /**
     * @param mixed $place_geo_lon
     */
    public function setPlaceGeoLon($place_geo_lon)
    {
        $this->place_geo_lon = $place_geo_lon;
    }

}
