fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group


fos_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_security_1.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

fos_user_resetting:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile