app_item_add:
    path:     /app/item/add/{rubric_id}
    defaults: { _controller: TooBigAppBundle:Item:add }
app_item_edit:
    path:     /app/item/{item_id}/edit
    defaults: { _controller: TooBigAppBundle:Item:edit }
app_item_copy:
    path:     /app/item/{item_id}/copy
    defaults: { _controller: TooBigAppBundle:Item:copy }
app_item_watch:
    path:     /app/item/{item_id}/watch
    defaults: { _controller: TooBigAppBundle:Item:watch }
app_item_unwatch:
    path:     /app/item/{item_id}/unwatch
    defaults: { _controller: TooBigAppBundle:Item:unwatch }
app_item_comment_add:
    path:     /app/item/{item_id}/comment/add
    defaults: { _controller: TooBigAppBundle:Item:addcomment }
app_item_comment_edit:
    path:     /app/item/{item_id}/comment/edit
    defaults: { _controller: TooBigAppBundle:Item:editcomment }
app_list_watch_items:
    path:     /app/items/watchlist
    defaults: { _controller: TooBigAppBundle:User:watchlist }
app_list_user_items:
    path:     /app/items/list
    defaults: { _controller: TooBigAppBundle:User:listUserItems }
app_user_profile_edit:
    path:     /app/profile/edit
    defaults: { _controller: TooBigAppBundle:User:editProfile }
app_file_upload:
    path:     /app/file/upload/
    defaults: { _controller: TooBigAppBundle:Item:upload }
app_list_model_by_brand:
    path:     /app/brand/model/
    defaults: { _controller: TooBigAppBundle:Model:listModelbyBrand }
app_list_size_by_sizetype:
    path:     /app/size/type/
    defaults: { _controller: TooBigAppBundle:Size:listSizebySizeType }
admin_list_model_by_brand:
    path:     /admin/brand/model/
    defaults: { _controller: TooBigAppBundle:Admin\AdminModel:listModelbyBrand }
admin_list_size_by_sizetype:
    path:     /admin/size/type/
    defaults: { _controller: TooBigAppBundle:Admin\AdminSize:listSizebySizeType }