parameters:

    iphp.admin.title: TooBig
    iphp.core.admin.rubric.class: Application\Iphp\CoreBundle\Admin\RubricAdmin
    #iphp.content.admin.content.class: Application\Iphp\ContentBundle\Admin\ContentAdmin


sonata_admin:
    title:      %iphp.admin.title%
    title_logo: /bundles/iphpcore/images/iphp.jpg
    templates:
        # default global templates
        layout: IphpCoreBundle::Admin/standard_layout.html.twig
        user_block: IphpCoreBundle::Admin/user_block.html.twig
        search: SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        #list_block: IphpCoreBundle::Admin/block_admin_list.html.twig
    dashboard:
        blocks:
           # display a dashboard block
           - { position: left, type: sonata.admin.block.admin_list }



    options:
            use_select2:    false



doctrine:
    dbal:
      types:
         json: Sonata\Doctrine\Types\JsonType




